name: Deploy to WordPress.org

on:
    release:
        types: [ released ]

jobs:
    build:
        uses: impress-org/givewp-github-actions/.github/workflows/wp-org-release.yml@master
        with:
            install_composer_packages: false
            wp_org_slug: google-places-reviews
            zip_name: google-places-reviews
            text_domain: google-places-reviews
        secrets:
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SLACK_ANNOUNCEMENT_WEBHOOK: ${{ secrets.SLACK_ANNOUNCEMENT_WEBHOOK }}
